# Generated by Django 5.2.14 on 2026-05-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mealrecord_date_alter_mealrecord_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BazarList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
